name: Tests

on: [ push,pull_request ]

jobs:
  uneditable:
    uses: esplora/.github/.github/workflows/phpunit-for-laravel.yaml@main
    with:
      os: '[ "ubuntu-latest", "windows-latest", "macos-latest" ]'
